# Generated by Django 5.2.10 on 2026-01-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='state',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
