# Generated by Django 5.2.10 on 2026-01-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_page_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/'),
        ),
    ]
