# Generated by Django 5.2.10 on 2026-01-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_page_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='state',
            field=models.IntegerField(choices=[(0, 'Borrador'), (1, 'Publicación')], default=1),
        ),
    ]
